### ISSUE TITLE
Prefer Foldable and Traversable classes to List stuff in BasicPrelude

### ISSUE THREAD

**Issue by DanBurton** [snoyberg/basic-prelude#15]
This is starting to stretch how "basic" BasicPrelude is, but if we're making it as a sort of "easy Haskell best practices" Prelude, then it would be good to replace list-biased functions with their Foldable and Traversable counterparts.

**Comment by fread2281** [comment]
Now that normal `Prelude` is doing this, I think `BasicPrelude` should. Like @sjoerdvisscher, BasicPrelude would be the perfect prelude for me if it would contain Foldable and Traversable
