### ISSUE TITLE
Export IsList

### ISSUE THREAD

**Issue by fread2281** [snoyberg/basic-prelude#52]
`IsList` (from `GHC.Exts`) is a useful typeclass that defines `fromList` and `toList`, and works with `OverloadedLists`. Note that `toList` should be hidden because it overlaps with `Foldable`.

**Comment by singpolyma** [comment]
This change would make the package only compile on pretty new versions of base.

**Comment by snoyberg** [comment]
We should hold off on this until GHC 7.10 is something we can rely upon, which isn't the case yet.
