### ISSUE TITLE
Lazy versions don’t export instances

### ISSUE THREAD

**Issue by Profpatsch** [snoyberg/basic-prelude#53]
Since `CorePrelude` only exports lazy versions like

    type LByteString = Data.ByteString.Lazy.ByteString

instances like e.g. `toString` are not re-exported.

Is there any way around that?

**Comment by DanBurton** [comment]
I'm not quite sure what you mean. All instances defined in the `Data.ByteString.Lazy` module *are* re-exported. The identifiers -- such as `toString` -- for *using* those instances are not necessarily re-exported.

Which `toString` are you referring to? Can you give a simple snippet of what you expected to work but didn't?

**Comment by Profpatsch** [comment]
Huh, you are right.

Ah, I know what confused me: `toString` is the function of `class IsString` but also a “normal” function exported by `Lazy.ByteString`.
