### ISSUE TITLE
Export Foldable and Traversable

### ISSUE THREAD

**Issue by jml** [snoyberg/basic-prelude#57]
Since the default Prelude now [exports](https://hackage.haskell.org/package/base-4.8.0.0/docs/Prelude.html#t:Foldable) [these](https://hackage.haskell.org/package/base-4.8.0.0/docs/Prelude.html#t:Traversable), it'd be nice if basic-prelude also exported them.

**Comment by DanBurton** [comment]
I agree.

**Comment by snoyberg** [comment]
I'm in favor of such a change, at least in theory. There are some details to work out: is this from CorePrelude or BasicPrelude? Do we export the functions using Foldable/Traversable as well? I'm open to lots of things, but haven't had a chance to think through the issues, and would be interested in others' opinions.

**Comment by jml** [comment]
Some opinions:

* basic-prelude already exports other types without exporting functions (e.g. Map), so exporting the Foldable and Traversable types seems like a good bare-minimum step regardless of whether functions get exported later
* [Elsewhere](http://www.yesodweb.com/blog/2013/01/so-many-preludes), you said that the test for whether something should go in Core vs Basic was "would classy-prelude use this also?". Here the answer is (I think), "it's irrelevant, since classy-prelude is already exporting all of Data.Foldable and Data.Traversable anyway".
* Current pattern seems to be that typeclass re-exports from Prelude are done in Core (although I don't quite understand why some other Prelude re-exports are done in Basic rather than Core).
* On exporting functions, since new Prelude has polymorphic versions of many functions, at least re-export those.
* As a relatively new user, re-exporting the things from Foldable & Traversable that the Prelude already re-exports would be the least surprising behaviour. I don't know whether exporting more would be a pleasant surprise.

**Comment by snoyberg** [comment]
* I agree that `Foldable`/`Traversable` from `CorePrelude` is fine
* Personally, I'm OK with exporting the `Foldable`/`Traversable` functions from `BasicPrelude`, but I'd like to hear from @DanBurton as well
* However, classy-prelude does *not* use the `Data.Foldable.*` functions, so those shouldn't be exported from `CorePrelude`. I think for consistency, we should apply the same rule to the `Data.Traversable.*` functions
* I'm OK with exporting more stuff than the 7.10 `Prelude` as well (e.g., I see no reason to avoid `<$>`)

**Comment by DanBurton** [comment]
My philosophy with BasicPrelude has been: take CorePrelude and bring it up
(at least) to feature parity with Prelude. So I think that these things
should definitely be exported from BasicPrelude.

CorePrelude tries to not be opinionated on such things. Given that
ClassyPrelude takes the "opinion" that MonoFoldable should be used instead,
I think CorePrelude should just leave them out.

On Monday, May 18, 2015, Michael Snoyman <notifications@github.com> wrote:

>
>    - I agree that Foldable/Traversable from CorePrelude is fine
>    - Personally, I'm OK with exporting the Foldable/Traversable functions
>    from BasicPrelude, but I'd like to hear from @DanBurton
>    <https://github.com/DanBurton> as well
>    - However, classy-prelude does *not* use the Data.Foldable.*
>    functions, so those shouldn't be exported from CorePrelude. I think
>    for consistency, we should apply the same rule to the
>    Data.Traversable.* functions
>    - I'm OK with exporting more stuff than the 7.10 Prelude as well
>    (e.g., I see no reason to avoid <$>)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snoyberg/basic-prelude/issues/57#issuecomment-103027448>
> .
>


-- 
-- Dan Burton

**Comment by snoyberg** [comment]
@DanBurton Just to be clear: when you say "I think CorePrelude should just leave them out", are you referring to just the functions, or the typeclasses themselves?

**Comment by DanBurton** [comment]
The functions (which could clash with different functions with the same name). It is harmless to export just the classes so that much should be fine.

**Comment by snoyberg** [comment]
OK, looks like we have a consensus then. @jml you interested in sending a PR for that change?

**Comment by jml** [comment]
Done. See #60

**Comment by snoyberg** [comment]
This has been released
