### ISSUE TITLE
Text version of error?

### ISSUE THREAD

**Issue by jml** [snoyberg/basic-prelude#58]
Since using basic-prelude, I find myself writing this a lot:

```
   Left e -> error $ Text.unpack $ "Reason this couldn't ever happen: " ++ show e
``` 

Before using basic-prelude, I didn't need `Text.unpack`. It would be nice if basic-prelude exported an `error` that expected `Text` rather than `String`.

**Comment by snoyberg** [comment]
How about `terror = error . Text.unpack`?

**Comment by chrisdone** [comment]
How about removing `error` from basic-prelude entirely? ;-P

[Ha ha only serious](http://c2.com/cgi/wiki?HaHaOnlySerious).

**Comment by jml** [comment]
@snoyberg, I've just (independently) added exactly that to my own code base :)

@chrisdone, I'd love to be able to encode all of my assertions into the type system, but I'm not good enough at Haskell yet. In the mean time, I'm going to use `error` to get informative error messages at runtime.

**Comment by snoyberg** [comment]
@jml If you send a PR for `terror`, I'll include it. I think it could go in either `CorePrelude` or `BasicPrelude`, unless someone has a reason for it not to go in `CorePrelude`.

**Comment by DanBurton** [comment]
@chrisdone has a point. Perhaps we should remove `undefined`, `error`, and `terror` from CorePrelude and move them to BasicPrelude instead.

**Comment by snoyberg** [comment]
I'm -1 on such a change, I find them useful. Especially `undefined`, which has a DEPRECATED pragma to remind you to go and fix your code ;)

**Comment by chrisdone** [comment]
Yeah, `undefined` is useful. I'm against `error` because it encourages stringly typed exceptions.

**Comment by snoyberg** [comment]
I'm opposed to using it too. However, I prefer a stringly typed exception to a completely useless bottom value (like `fromJust` or the like) which happens all too often. I consider exposing `error` a useful compromise for people who won't take the time to define exception types.

**Comment by chrisdone** [comment]
Indeed, in seriousness it belongs there.

**Comment by snoyberg** [comment]
This got added, closing
