### ISSUE TITLE
`asum` missing

### ISSUE THREAD

**Issue by PierreR** [snoyberg/basic-prelude#64]
I am debating on using `basic-prelude` or `base-prelude`.

The fact that `basic-prelude` doesn't expose `asum` from `Data.Foldable` is currently preventing me to consider `basic-prelude`.

Is there any reason why it is not included ? Would you consider including it ?

**Comment by PierreR** [comment]
That said, if I use `CorePrelude` instead I am going to miss `empty` from `Control.Applicative`.

**Comment by snoyberg** [comment]
I don't see a problem with adding it. Dan, any thoughts?

**Comment by DanBurton** [comment]
Sounds fine to me. :+1:

**Comment by snoyberg** [comment]
@PierreR Want to send a PR to add that function? If you notice others like this that you think would be good additions, I think both Dan and I are unlikely to oppose them.

**Comment by PierreR** [comment]
@snoyberg Sure I will do the PR. Thanks.

**Comment by PierreR** [comment]
@snoyberg Just to be more precise I would like to add `asum` and `empty` to the CorePrelude module. Is that alright ?
As a note, after further investigation, I won't use the `BasicPrelude` module as I quite dislike the `empty = mempty` re-definition (isn't this conflicting with empty from Alternative ?)

**Comment by snoyberg** [comment]
I agree that `empty = mempty` was a mistake on my part. I'd be in favor of adding a deprecation message to that `empty` telling users to use `mempty` instead, and in the next major release replacing `empty` with the reexport from `Alternative`.
