### ISSUE TITLE
‘show’ is not a (visible) method of class ‘Show’

### ISSUE THREAD

**Issue by jparoz** [snoyberg/basic-prelude#67]
When declaring a new instance of the typeclass Show:

```haskell
{-# LANGUAGE NoImplicitPrelude, OverloadedStrings #-}
module PreludeTest where

import BasicPrelude

data Foo = Foo { bar :: Int, baz :: Bool }

instance Show Foo where
    show foo = "Foo { bar = " ++ show (bar foo) ++
                   ", baz = " ++ show (baz foo) ++ " }"
```

Trying to compile this code gives the error `‘show’ is not a (visible) method of class ‘Show’`. I can't seem to find any workarounds that don't involve simply hiding the relevant imports from BasicPrelude, and importing them directly from GHC.Show.

This may be a simple case of PEBKAC, and I'm just missing something obvious, but I can't think what it could possibly be. Is this the intended behaviour?

**Comment by snoyberg** [comment]
No, this is the way `BasicPrelude` works right now. In `ClassyPrelude`, we ultimately decided to revert `show` to the member of the `Show` typeclass and provide an additional `tshow` function. I'm OK with doing the same here. @DanBurton any thoughts?

**Comment by DanBurton** [comment]
I think the workaround is `import qualified Prelude` and then refer to `Prelude.show` as necessary.

I think it makes sense to take the classy prelude approach with `tshow`.

**Comment by snoyberg** [comment]
I pushed a commit for this to master. Can you review before I release to Hackage?

**Comment by singpolyma** [comment]
I the proposed change goes in, then we'll have a core prelude function that returns String and not Text. Seems counter to the design of the Prelude here. Since you can do a qualified import for instance declarations, and using show is much more common than manual instance declarations, I think it would be better to keep consistency vs this change.

Just my 2 cents
