### ISSUE TITLE
Provided ``sum`` is not general enough

### ISSUE THREAD

**Issue by kozross** [snoyberg/basic-prelude#69]
From what I can tell, the ``sum`` function provided by ``BasicPrelude`` has type ``(Num a) => [a] -> a``, while the one in ``Data.List`` (at least, most recently) has the type ``(Foldable t, Num a) => t a -> a``, which is more general and useful. Is there a reason for this choice?

**Comment by snoyberg** [comment]
Good catch, want to send a PR to fix it?

**Comment by kozross** [comment]
@snoyberg I believe PR #68 already did that.

**Comment by snoyberg** [comment]
Dan and I disagreed with the conditional approach in that PR. Would you be
able to send a new PR that isn't conditional like that one?

**Comment by snoyberg** [comment]
Resolved by 32d67a4c4083818a7e3b899d4325b6e90325bc20
