### ISSUE TITLE
Export `for`, `for_`, `traverse_` and `sequenceA_`

### ISSUE THREAD

**Issue by howsiwei** [snoyberg/basic-prelude#72]
Currently `BasicPrelude` export `forM`, `forM_`, `mapM_` and `sequence_`, but not the more general `for`, `for_`, `traverse_` and `sequenceA_` which work on `Applicative` instead of `Monad`. Any plan to include them?

**Comment by snoyberg** [comment]
I see no problem with such inclusions, PR welcome.
