### ISSUE TITLE
Generalize `concat`, `concatMap` and `intercalate`?

### ISSUE THREAD

**Issue by howsiwei** [snoyberg/basic-prelude#73]
Currently they have the following types:
```haskell
concat :: Monoid w => [w] -> w
concatMap :: Foldable t => (a -> [b]) -> t a -> [b]
intercalate :: Monoid w => w -> [w] -> w
```
which can be potentially generalized to
```haskell
concat :: (Foldable t, Monoid w) => t w -> w
concatMap :: (Foldable t, Monoid w) => (a -> w) -> t a -> w
intercalate :: (Foldable t, Monoid w) => w -> t w -> w
```

in particular `concatMap` is just `foldMap`. The only reason I see why not to do this is that a generic implementation may be inefficient for some `(Foldable t, Monoid w)` instances.

**Comment by snoyberg** [comment]
I think this diverges pretty far from practice, which may not be desired for `BasicPrelude`. Recommending `foldMap` and `fold` may be more in line with common practice. I don't have the same feelings about `intercalate.`

**Comment by howsiwei** [comment]
Personally I'm fine with the current `concatMap` and `intercalate`, but I'm feel uneasy about `concat` which is different but not more general than the standard Prelude `concat` which has type `Foldable t => t [a] -> [a]`.

**Comment by snoyberg** [comment]
Ah, good point, I hadn't thought about concat. I don't have a strong
feeling about what its type should end up as to be honest, but I agree with
you about some level of consistency.

**Comment by snoyberg** [comment]
Thanks for all of the PRs, the new version of basic-prelude (0.7.0) is now on Hackage. Can this issue also be closed, or is there more work to be done here too?

**Comment by howsiwei** [comment]
No plan to do anything about it now
