### ISSUE TITLE
Strict `minimum`, `maximum`, `minimumBy` and `maximumBy`?

### ISSUE THREAD

**Issue by howsiwei** [snoyberg/basic-prelude#74]
Currently the exported `sum` and `product` are strict, but not `minimum`, `maximum`, `minimumBy` and `maximumBy`, which seems inconsistent.

**Comment by snoyberg** [comment]
That's a good catch, those should be fixed. Are you interested in sending such an improvement?

**Comment by howsiwei** [comment]
This issue is more complicated than I thought. See [Note [maximumBy/minimumBy space usage]](https://hackage.haskell.org/package/base-4.10.0.0/docs/src/Data.Foldable.html#maximumBy). For now the solution seems to be just changing `maximumBy` and `minimumBy` to use `foldl1` for `base < 4.10.0` and leave the rest to GHC's strictness analysis.
